WEB-3357: Nestjs - migrate campaign admin CRUD operations
thegoodparty/gp-api pull request #18
Opened 2024-12-03 16:07 UTC by oldfashionedrobot

- Adds Admin Module to house admin controllers
- Adds AdminCampaigns controller + service for campaign CRUD
- Updates the way I was using Zod + ZodValidationPipe for campaigns CRUD (cleaner to use classes and not have to manually pass in the schema object to ZodValidationPipe instances)
- Updated the raw SQL query in the `campaignsService` to use Prisma query objects
- Installed `validator` package for premade validators for many cases

2024-12-03 20:47 UTC, RavenHursT commented on src/admin/campaigns/adminCampaigns.controller.ts
> +  async create(@Body() body: AdminCreateCamapaignSchema) {
Typo here.

2024-12-04 02:44 UTC, tomer-tgp requested changes

2024-12-04 02:44 UTC, tomer-tgp commented on prisma/schema/user.prisma
> +  campaign
admin?

2024-12-04 02:44 UTC, tomer-tgp commented on src/admin/campaigns/adminCampaigns.service.ts
> +      return 'Email already in use'
this should probably return a 409 not a 400

2024-12-04 02:44 UTC, tomer-tgp commented on prisma/schema/user.prisma
> +  campaign
or we can add "isAdmin" to User

2024-12-04 16:31 UTC, tomer-tgp approved these changes

2024-12-04 16:31 UTC, merged